import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/shared/components/NavBar.component";
import HamburguerMenu from "@/shared/components/HamburguerMenu.components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar/>
        {/* <HamburguerMenu/> */}
        {children}
      </body>
    </html>
  );
}
